# Generated by Django 4.2.19 on 2025-02-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_description_alter_lesson_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('community_health', 'Community Health'), ('obstetrics', 'Obstetrics & Gynecology'), ('pediatrics', 'Pediatrics'), ('mental_health', 'Mental Health')], default='community_health', max_length=50),
        ),
    ]
