# Generated by Django 4.2.19 on 2025-02-26 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='additional_material',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_content',
        ),
        migrations.RemoveField(
            model_name='module',
            name='video_content',
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('community_health', 'Community Health'), ('obstetrics', 'Obstetrics & Gynecology'), ('pediatrics', 'Pediatrics')], default='community_health', max_length=50),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='courses.lesson')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('material_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_materials', to='courses.lesson')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
