# Generated by Django 4.2.19 on 2025-10-26 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0012_lesson_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
            ],
            options={
                'verbose_name': 'Ebook Category',
                'verbose_name_plural': 'Ebook Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=260, unique=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='ebook_covers/')),
                ('file', models.FileField(help_text='Upload PDF file', upload_to='ebooks/')),
                ('published', models.BooleanField(default=True)),
                ('allow_preview', models.BooleanField(default=True, help_text='If false, prevent in-site preview')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ebooks', to='courses.ebookcategory')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_ebooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='courses_ebo_slug_25abe4_idx'), models.Index(fields=['published'], name='courses_ebo_publish_c51c96_idx')],
            },
        ),
    ]
