# Generated by Django 4.2.19 on 2025-10-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('community_health', 'Community Health'), ('obstetrics', 'Obstetrics & Gynecology'), ('pediatrics', 'Pediatrics'), ('cloud_computing', 'Cloud Computing'), ('python_programming', 'Python Programming'), ('data_science', 'Data Science'), ('django_framework', 'Django Framework')], default='community_health', max_length=50),
        ),
    ]
