# Generated by Django 4.2.19 on 2026-04-03 16:09

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, storage=courses.models.get_raw_storage, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='file',
            field=models.FileField(help_text='Upload PDF file', storage=courses.models.get_raw_storage, upload_to='ebooks/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, storage=courses.models.get_raw_storage, upload_to='lesson_pdfs/'),
        ),
    ]
