# Generated by Django 4.2.19 on 2026-04-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_certificate_certificate_file_alter_ebook_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('community_health', 'Community Health'), ('obstetrics', 'Obstetrics & Gynecology'), ('pediatrics', 'Pediatrics'), ('cloud_computing', 'Cloud Computing'), ('python_programming', 'Python Programming'), ('data_science', 'Data Science'), ('django_framework', 'Django Framework'), ('medical_innovation', 'Medical Innovation')], default='community_health', max_length=50),
        ),
    ]
