# Generated by Django 4.2.19 on 2026-04-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_course_actual_price_course_is_premium_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.RemoveField(
            model_name='module',
            name='content',
        ),
        migrations.RemoveField(
            model_name='module',
            name='image_content',
        ),
        migrations.RemoveField(
            model_name='module',
            name='objectives',
        ),
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
