# Generated by Django 4.2.19 on 2026-04-15 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_alter_lesson_options_alter_module_options_and_more'),
        ('courses', '0099_ebook_created_by'),
    ]

    operations = [
    ]
