# Generated by Django 4.2.19 on 2026-04-17 22:00

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0101_populate_ebook_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='objectives',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='objectives',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
