# Generated by Django 4.2.19 on 2026-04-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0102_alter_course_objectives_alter_lesson_objectives'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='estimated_duration',
            field=models.PositiveIntegerField(default=5, help_text='Estimated time to complete this lesson in minutes.'),
        ),
    ]
