# Generated by Django 4.2.19 on 2026-04-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_groupinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='message_attachments/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='message_attachments/%Y/%m/%d/'),
        ),
    ]
