# Generated by Django 4.2.19 on 2026-04-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_directmessage_attachment_groupmessage_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
