# Generated by Django 4.2.19 on 2026-04-15 08:44

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_alter_directmessage_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitygroup',
            name='icon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[400, 400], upload_to='group_icons/%Y/%m/%d/'),
        ),
    ]
