# Generated by Django 4.2.19 on 2025-10-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_certificate'),
        ('users', '0003_subscribeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='earned_badges',
            field=models.ManyToManyField(blank=True, related_name='awarded_to', to='courses.course'),
        ),
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
