# Generated by Django 4.2.19 on 2026-04-03 15:54

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='default.jpg', force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[600, 600], upload_to='profiles/'),
        ),
    ]
