# Generated by Django 4.2.19 on 2026-04-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_seen_tour',
            field=models.BooleanField(default=False),
        ),
    ]
